### ISSUE TITLE
bot is bad

### ISSUE THREAD

**Issue by a11ce** [dilanx/GamerBot#1]
see attached

<img width="663" alt="Screen Shot 2021-04-04 at 13 09 23" src="https://user-images.githubusercontent.com/26006608/113517672-0f7d0400-9547-11eb-9d2d-0cfb58829276.png">

**Comment by dilanx** [comment]
Ahh yes all the omegaluls didn't save what an issue hmm yes I will definitely be fixing this hmm except I won't
